language: node_js
install: npm install
script: npm run $COMMAND
branches:
  only:
    - master
    - develop
env:
  global:
    # saucelabs credentials
    # subaccount of "opensauce-algolia"
    - SAUCE_USERNAME=algoliasearch-js
    - secure: "oKl1RMuEO9bYoKevbFeFX72M2eV+DIJG/9UGMP4oLb3z5B8T5xAlQSEt8Lp0Zms6qqA+4hAQhZTKXDtdpx7NK+SuqYiv4oR9hdiJBbrRXIRuY86R2T/opO/RlBETL+7Y2R1AGM/kZzyiZSFqN9slGVzWziBtLJjJ4ncoceE8izs="

    # integration tests credentials
    - secure: "UnpKy2vOhmkbAXV9J1miZMCVM7VeUl9SyeoN4iFj65KD26wPODdXFjaxiVYM7YvQiUj61HraB6iqk2Vt/W842ACxNl2mOjSTHQXNI7qbtdIlLs0ABdJwjXsCxBtmAIi2GEj/JiDU/duF11/VgkxwBWvIGYEkOD+9c2bJp382xPQ="
    - secure: "gMSrjKP4bFYh/cUnO3JDXV+NW6aCdzP6Luwn2QJhml0Ump1a0fomHJUsjELaTpzel9CiONbf7D8bmEyN8woFQq8wa+wltVAzPpbNhYMclJmFV6sKOlGcGn3f/SDv5MiUBuUtyMRgnPv2OEoafQ40mSN/5ELT7PQzYXqxp+EGhTM="

    # parse test credentials
    - secure: "KJ5+bYlg0MCX8tAQM6IRBZi43SRPgxj6VSxEyvdQn40LYShlvDIFLgKDQ+Acg5U5k0dQ3HMWsAfrJl/T/pQDmh53g14yZrDZYQeAg0gT25RYUYIY3ByrwcQUhriOqU4ivj2neVBiBJxZ4f7Scx0RBk6OTgvAU/Cc+37apDdDKRk="
    - secure: "ZJSK5Mgd/Gmew/5V5e7nd/ArVhIngB825+phWYF00/T9sKYY9P83JQGVn9Iwf/iGBI6lgabS79CwwmaetCzjQa4YxsOObmaMgho/brqlci9AilbksI3UhNVMehFt2Pr1RZQMmGKk+Uot3RKqna5fvyZdtbOw0jGef/H1oYge9HY="
matrix:
  fast_finish: true
  include:
    # First we try to build the browser files
    - node_js: '0.12'
      env: COMMAND=build APP_ENV=production

    # Browser integration tests, real browsers
    - node_js: '0.12'
      env: COMMAND=test-browser-integration BROWSERS=integration APP_ENV=production

    # Integration tests, nodejs
    - node_js: '0.12'
      env: COMMAND=test-node-integration
    - node_js: '0.10'
      env: COMMAND=test-node-integration
    - node_js: 'iojs-v2.2.1'
      env: COMMAND=test-node-integration

    # Browser unit tests, phantom
    - node_js: '0.12'
      env: COMMAND=test-phantom-unit APP_ENV=production

    # Browser unit test, real browsers
    # In pull requests, the first "DESKTOP" tests will be run on all
    # latest browsers only (desktop + mobile)
    - node_js: '0.12'
      env: COMMAND=test-browser-unit BROWSERS=desktop
    # This task will be ignored in pull requests
    - node_js: '0.12'
      env: COMMAND=test-browser-unit BROWSERS=mobile

    # Node.js unit tests
    - node_js: '0.12'
      env: COMMAND=test-node-unit
    - node_js: '0.10'
      env: COMMAND=test-node-unit
    - node_js: iojs-v2.2.1
      env: COMMAND=test-node-unit

    # Parse build test
    - node_js: '0.12'
      env: COMMAND=test-parse-cloud

    # Linting
    - node_js: '0.12'
      env: COMMAND=lint
