aliases:
  - &install_yarn_version
    name: Install specific Yarn version
    command: |
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
      echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV

  - &restore_yarn_cache
    name: Restore Yarn cache
    keys:
      - yarn-{{ .Branch }}-packages-{{ checksum "yarn.lock" }}

  - &save_yarn_cache
    name: Save Yarn cache
    key: yarn-{{ .Branch }}-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

  - &run_yarn_install
    name: Install dependencies
    command: yarn install

defaults: &defaults
  working_directory: ~/algoliasearch-client-javascript
  parameters:
    version:
      type: string
  docker:
    - image: circleci/node:<< parameters.version >>

version: 2.1
jobs:
  test_build:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/node:<< parameters.version >>
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Build & Test packages size
          command: yarn test:build

  test_lint:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Lint tests
          command: yarn test:lint

  test_types:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Lint tests
          command: yarn test:types

  test_unit:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Unit Tests
          command: yarn test:unit --maxWorkers=4

  test_browser:
    <<: *defaults
    steps:
      - checkout
      - run: *install_yarn_version
      - restore_cache: *restore_yarn_cache
      - run: *run_yarn_install
      - save_cache: *save_yarn_cache
      - run:
          name: Install Sauce Connect Proxy
          command: |
            cd /tmp
            curl https://saucelabs.com/downloads/sc-4.5.4-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            chmod a+x sc-4.5.4-linux/bin/sc
            sudo cp sc-4.5.4-linux/bin/sc /usr/local/bin
            sc --version
      - run:
          name: Open Sauce Connect Proxy Tunnel
          background: true
          command: |
            # startup saucelabs tunnel as background task (its a blocking command)
            sc -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} -f --tunnel-identifier ${CIRCLE_BUILD_NUM}
            #wait for sauce tunnel up to 1 minute
            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
      - run:
          name: Browser tests
          command: yarn test:browser-ci
      - run:
          name: Close Sauce Connect Tunnels
          command: killall sc
workflows:
  version: 2
  ci:
    jobs:
      - test_unit:
          version: '8'
      - test_unit:
          version: '10'
      - test_unit:
          version: '11'
      - test_unit:
          version: '12'
      - test_lint:
          version: '12'
      - test_types:
          version: '12'
      - test_build:
          version: '12'
      - test_browser:
          version: '12'
